services:
  web:
    profiles: ["dev", "server"]
    container_name: TCAapp
    restart: always
    build: ./TCA
    command: gunicorn tablero_control.wsgi:application --bind 0.0.0.0:8000 --reload --workers 5 --threads 2 --timeout 60
    # command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env.dev
    links:
      - db
    volumes:
      - ./media_volume:/src/TCA/data/media
      - ./static_volume:/src/TCA/data/static
      - ./TCA/estadistica:/src/TCA/estadistica
      - ./TCA/usuarios:/src/TCA/usuarios
      - ./TCA/dashboard:/src/TCA/dashboard
      - ./TCA/supervision:/src/TCA/supervision
      - ./TCA/tablero_control:/src/TCA/tablero_control
      - ./TCA/panel:/src/TCA/panel
      - ./TCA/zdata:/src/TCA/zdata
  
  vite:
    profiles: ["dev"]
    container_name: TCAvite
    build: ./vite
    command: npm run dev
    volumes:
      - ./vite:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - VITE_BACKEND_URL=http://localhost:8000

  db:
    profiles: ["dev", "server"]
    container_name: databasePG
    restart: always
    image: postgres:16.4-alpine
    shm_size: 128mb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db

  nginx:
    profiles: ["dev", "server"]
    container_name: TcaNginx
    build: ./nginx
    expose:
      - 443
    ports:
      - 443:443
      - 80:80
    links:
      - web
    volumes:
      - ./static_volume:/src/TCA/data/static
      - ./media_volume:/src/TCA/data/media
      - ./certificados:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    environment:
      - VIRTUAL_HOST=tca.inm.gob.mx
      - LETSENCRYPT_HOST=tca.inm.gob.mx
      - LETSENCRYPT_EMAIL=dgcor.rui23@gmail.com